/**
 * Bundles the coach handler into api/coach.js for Vercel.
 *
 * Why bundle instead of deploying the source: every file in server/ and shared/
 * imports with explicit .ts extensions, because that is what `node --test
 * --experimental-strip-types` requires. Vercel's edge bundler rejects .ts
 * import specifiers outright ("referencing unsupported modules"). Bundling
 * collapses the whole graph into one file, so Vercel never resolves anything.
 *
 * The output is COMMITTED, because Vercel discovers functions by scanning the
 * repo, not by trusting the build to produce them. Run `npm run build` before
 * pushing any change under server/ or shared/.
 */
import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';

await mkdir('api', { recursive: true });

await build({
  entryPoints: { coach: 'server/api/coach.ts' },
  outdir: 'api',
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  // Vercel installs this from package.json; bundling it risks the edge size cap.
  external: ['@google/genai', '@google/genai/web'],
  banner: {
    js: '// GENERATED by scripts/build-api.mjs — do not edit. Run `npm run build`.',
  },
  logLevel: 'info',
});
