/**
 * Bundles the coach handler into api/coach.js for Vercel.
 *
 * Why bundle instead of deploying the source: every file in server/ and shared/
 * imports with explicit .ts extensions, because that is what `node --test
 * --experimental-strip-types` requires. Vercel's edge bundler rejects .ts
 * import specifiers outright ("referencing unsupported modules"). Bundling
 * collapses the whole graph into one file, so Vercel never resolves anything.
 *
 * The output is COMMITTED, because Vercel discovers functions by scanning the
 * repo, not by trusting the build to produce them. Run `npm run build` before
 * pushing any change under server/ or shared/.
 *
 * EVERYTHING is bundled, including @google/genai, so the function has no
 * runtime resolution to do at all.
 *
 * Two constraints pin this configuration, and both are easy to trip over:
 *   - runtime is nodejs, not edge. The edge sandbox hung on boot with this
 *     bundle — even OPTIONS timed out, and OPTIONS returns 204 before it
 *     touches Gemini.
 *   - the SDK is imported from @google/genai/web, and platform is 'browser'.
 *     The Node build of the SDK does a dynamic require("child_process") for
 *     gcloud auth, which esbuild cannot bundle. The web build has no such call
 *     and runs perfectly well under Node.
 */
import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';

await mkdir('api', { recursive: true });

await build({
  entryPoints: { coach: 'server/api/coach.ts' },
  outdir: 'api',
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  banner: {
    js: '// GENERATED by scripts/build-api.mjs — do not edit. Run `npm run build`.',
  },
  logLevel: 'info',
});
