/**
 * Bundles the coach handler into api/coach.js for Vercel.
 *
 * Why bundle instead of deploying the source: every file in server/ and shared/
 * imports with explicit .ts extensions, because that is what `node --test
 * --experimental-strip-types` requires. Vercel's edge bundler rejects .ts
 * import specifiers outright ("referencing unsupported modules"). Bundling
 * collapses the whole graph into one file, so Vercel never resolves anything.
 *
 * The output is COMMITTED, because Vercel discovers functions by scanning the
 * repo, not by trusting the build to produce them. Run `npm run build` before
 * pushing any change under server/ or shared/.
 *
 * EVERYTHING is bundled, including @google/genai. Edge functions have no
 * node_modules at runtime, so an external import silently fails to resolve and
 * the function hangs on boot — no error, no response, just a timeout. The full
 * bundle is ~73 KB gzipped against a 1 MB limit, so there is no reason to risk
 * it.
 */
import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';

await mkdir('api', { recursive: true });

await build({
  entryPoints: { coach: 'server/api/coach.ts' },
  outdir: 'api',
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  banner: {
    js: '// GENERATED by scripts/build-api.mjs — do not edit. Run `npm run build`.',
  },
  logLevel: 'info',
});
