// GENERATED by scripts/build-api.mjs — do not edit. Run `npm run build`.

// shared/contracts.ts
var MISCONCEPTION_IDS = [
  "TS_BRUTE_FORCE_ONLY",
  "TS_COMPLEMENT_CONFUSION",
  "TS_MAP_DIRECTION_FLIPPED",
  "TS_INSERT_BEFORE_CHECK",
  "TS_RETURNS_VALUES_NOT_INDICES",
  "TS_OFF_BY_ONE_INNER_LOOP",
  "NONE"
];
var MISCONCEPTION_LABELS = {
  TS_BRUTE_FORCE_ONLY: "nested loops, no hash-map insight",
  TS_COMPLEMENT_CONFUSION: "does not see target - num as the search key",
  TS_MAP_DIRECTION_FLIPPED: "stores index -> value instead of value -> index",
  TS_INSERT_BEFORE_CHECK: "inserts current num first, then matches it with itself",
  TS_RETURNS_VALUES_NOT_INDICES: "returns the values rather than their positions",
  TS_OFF_BY_ONE_INNER_LOOP: "inner loop starts at 0 or i, not i + 1",
  NONE: "approach is sound \u2014 praise and get out of the way"
};
var SKILL_IDS = [
  "hash_maps",
  "complexity_analysis",
  "array_traversal",
  "problem_decomposition"
];
var MODALITIES = ["question", "analogy", "visual", "video"];
var HELP_ACTIONS = ["hint", "analogy", "visual", "video", "retry"];
var CONFIDENCE_FLOOR = 0.55;
var MAX_CODE_LINES_IN_RESPONSE = 3;
var DO_NOT_REPEAT_WINDOW = 6;
var PREFERRED_MODALITY_THRESHOLD = 2;

// shared/profile.ts
function countFor(profile, id) {
  return profile.misconceptionCounts[id] ?? 0;
}
function deliveredFor(profile, id) {
  return profile.deliveredInterventions[id] ?? [];
}
function derivePreferredModality(wins) {
  let best = null;
  let bestCount = 0;
  for (const m of MODALITIES) {
    if (wins[m] > bestCount) {
      best = m;
      bestCount = wins[m];
    }
  }
  return bestCount >= PREFERRED_MODALITY_THRESHOLD ? best : null;
}
function applyProfileDelta(profile, delta, now) {
  const next = {
    ...profile,
    skills: { ...profile.skills },
    misconceptionCounts: { ...profile.misconceptionCounts },
    deliveredInterventions: { ...profile.deliveredInterventions },
    priorCoachMessages: [...profile.priorCoachMessages],
    modalityWins: { ...profile.modalityWins },
    updatedAt: now
  };
  for (const [skill, state] of Object.entries(delta.skillUpdates)) {
    next.skills[skill] = state;
  }
  if (delta.incrementMisconception && delta.incrementMisconception !== "NONE") {
    const id = delta.incrementMisconception;
    next.misconceptionCounts[id] = (next.misconceptionCounts[id] ?? 0) + 1;
  }
  if (delta.recordDelivered) {
    const { misconceptionId, modality } = delta.recordDelivered;
    const seen = next.deliveredInterventions[misconceptionId] ?? [];
    if (!seen.includes(modality)) {
      next.deliveredInterventions[misconceptionId] = [...seen, modality];
    }
    next.lastIntervention = { misconceptionId, modality, at: now };
  }
  if (delta.creditModality) {
    next.modalityWins[delta.creditModality] += 1;
    next.preferredModality = derivePreferredModality(next.modalityWins);
  }
  if (delta.appendCoachMessage) {
    next.priorCoachMessages = [
      ...next.priorCoachMessages,
      delta.appendCoachMessage
    ].slice(-DO_NOT_REPEAT_WINDOW);
  }
  return next;
}
function summariseProfile(profile) {
  const improving = SKILL_IDS.filter((s) => profile.skills[s] === "improving");
  const parts = [];
  if (improving.length > 0) {
    parts.push(`${improving.join(", ").replace(/_/g, " ")} \u2192 improving`);
  }
  if (profile.preferredModality) {
    const phrasing = {
      question: "Questions get you unstuck fastest",
      analogy: "Real-life examples work best for you",
      visual: "Visual explanations work best for you",
      video: "Video walkthroughs work best for you"
    };
    parts.push(phrasing[profile.preferredModality]);
  }
  return parts.join(". ") || "Still getting to know how you think.";
}

// server/lib/escalation.ts
var ACTION_FOR = {
  question: "hint",
  analogy: "analogy",
  visual: "visual",
  video: "video"
};
function ladderFor(count) {
  if (count <= 1) return { level: 1, modality: "question", deliver: true };
  if (count === 2) return { level: 2, modality: "question", deliver: true };
  if (count === 3) return { level: 3, modality: "analogy", deliver: true };
  if (count === 4) return { level: 4, modality: "visual", deliver: true };
  return { level: null, modality: "video", deliver: true };
}
var CONTENT = ["analogy", "visual", "video"];
function firstUnused(delivered, from) {
  const start = Math.max(CONTENT.indexOf(from), 0);
  for (let i = start; i < CONTENT.length; i += 1) {
    if (!delivered.includes(CONTENT[i])) return CONTENT[i];
  }
  for (let i = 0; i < start; i += 1) {
    if (!delivered.includes(CONTENT[i])) return CONTENT[i];
  }
  return null;
}
function whyBlocked(action, delivered, current, exhausted) {
  const modality = MODALITIES.find((m) => ACTION_FOR[m] === action);
  if (modality && delivered.includes(modality)) {
    return "We've already been down that road. Let's try a different angle.";
  }
  if (exhausted) {
    return "I've used every trick I have on this one. Talk it through with me instead.";
  }
  switch (action) {
    case "analogy":
      return "Give the question above a real shot first \u2014 then I'll reach for a comparison.";
    case "visual":
      return "Let's try one more idea in words. I'll draw it if that doesn't land.";
    case "video":
      return "A video is a big detour this early. Ask again if you're still stuck.";
    case "hint":
      return current === "video" ? "I'm out of hints \u2014 the video covers the rest better than I can." : "Answer what I just asked and the next hint will actually be useful.";
    default:
      return "Not right now.";
  }
}
function decideIntervention(profile, misconceptionId) {
  const count = countFor(profile, misconceptionId);
  const delivered = deliveredFor(profile, misconceptionId);
  const base = ladderFor(count);
  let modality = base.modality;
  let reason = `count=${count} -> ladder ${base.modality}`;
  const wins = profile.modalityWins[profile.preferredModality ?? "question"] ?? 0;
  if (count === 2 && profile.preferredModality && wins >= PREFERRED_MODALITY_THRESHOLD && !delivered.includes(profile.preferredModality)) {
    modality = profile.preferredModality;
    reason = `count=2 + preferredModality=${modality} (${wins} wins) -> override`;
  }
  let exhausted = false;
  if (modality !== "question" && delivered.includes(modality)) {
    const next = firstUnused(delivered, modality);
    if (next) {
      reason += ` -> ${modality} already delivered, advancing to ${next}`;
      modality = next;
    } else {
      exhausted = true;
      modality = "question";
      reason += " -> every modality exhausted, falling back to a fresh question";
    }
  }
  const level = base.level;
  const askComprehension = modality === "visual" || modality === "video" || count >= 4;
  const offered = ["retry"];
  if (!exhausted) {
    if (level !== null && level < 4) offered.push("hint");
    if (count >= 2) {
      const next = firstUnused([...delivered, modality], modality);
      if (next) offered.push(ACTION_FOR[next]);
    }
  }
  const blocked = HELP_ACTIONS.filter((a) => !offered.includes(a)).map(
    (action) => ({ action, reason: whyBlocked(action, delivered, modality, exhausted) })
  );
  return {
    hintLevel: level,
    modality,
    deliver: base.deliver,
    offeredActions: offered,
    blockedActions: blocked,
    askComprehension,
    doNotRepeat: profile.priorCoachMessages,
    exhausted,
    reason
  };
}
function creditFor(profile, corrected) {
  if (!corrected) return null;
  return profile.lastIntervention?.modality ?? null;
}

// server/lib/fallbacks.ts
var FALLBACK_RESPONSES = {
  TS_BRUTE_FORCE_ONLY: "That will find the answer every single time, so let's leave correctness alone. Here's what I'm curious about: when you're standing on the number 2, what exactly are you asking the rest of the array for?",
  TS_COMPLEMENT_CONFUSION: "You're checking pairs as you meet them. Try this instead \u2014 if I tell you the current number is 7 and the target is 9, can you name the number you are hunting for before you look at a single other element?",
  TS_MAP_DIRECTION_FLIPPED: 'Your table lets you ask "what number lives at index 3?" \u2014 but read your own lookup back to me. At that moment, which of the two do you already have in your hand, and which one are you trying to find?',
  TS_INSERT_BEFORE_CHECK: "Walk your code by hand on nums = [3, 2, 4] with target 6. When 3 goes looking for its partner, who does it find \u2014 and is that a pair of two different elements?",
  TS_RETURNS_VALUES_NOT_INDICES: "Read the last sentence of the problem statement out loud. Is it asking you to hand back the two numbers, or something about where they were sitting?",
  TS_OFF_BY_ONE_INNER_LOOP: "Your two loops can both be sitting on the same element at the same time. On paper, what is the very first pair they hand you \u2014 and are those genuinely two different positions in the array?",
  NONE: "That's the right shape. One pass, and you're using what you've already seen instead of looking ahead. Go write it \u2014 I'll be here if the edge cases bite."
};
var LEARNING_GOALS = {
  TS_BRUTE_FORCE_ONLY: "Recognising when a lookup can replace a scan.",
  TS_COMPLEMENT_CONFUSION: 'Turning "find a pair" into "find one known value".',
  TS_MAP_DIRECTION_FLIPPED: "Choosing what to key a lookup table on.",
  TS_INSERT_BEFORE_CHECK: "Ordering your operations so an element cannot match itself.",
  TS_RETURNS_VALUES_NOT_INDICES: "Reading the problem statement as a contract.",
  TS_OFF_BY_ONE_INNER_LOOP: "Reasoning about loop bounds without running the code.",
  NONE: "Committing to an approach and writing it."
};
function fallbackFor(id, options = {}) {
  const {
    hintLevel = id === "NONE" ? null : 1,
    modality = "question",
    offeredActions = id === "NONE" ? ["retry"] : ["hint", "analogy", "retry"],
    note
  } = options;
  const message = FALLBACK_RESPONSES[id];
  return {
    misconceptionId: id,
    confidence: CONFIDENCE_FLOOR,
    message,
    hintLevel,
    modality,
    offeredActions,
    blockedActions: [],
    analogy: null,
    visual: null,
    video: null,
    comprehensionQuestion: null,
    profileDelta: {
      skillUpdates: {},
      incrementMisconception: id === "NONE" ? null : id,
      recordDelivered: id === "NONE" ? null : { misconceptionId: id, modality },
      creditModality: null,
      appendCoachMessage: message,
      summary: ""
    },
    learningGoal: LEARNING_GOALS[id],
    meta: { fallbackUsed: true, model: "fallback", latencyMs: 0, note }
  };
}

// server/lib/gemini.ts
import { GoogleGenAI } from "@google/genai/web";
var MODEL = process.env.COACH_MODEL ?? "gemini-3.1-flash-lite";
var TIMEOUT_MS = 9e3;
var client = null;
function getClient() {
  if (!process.env.GEMINI_API_KEY) return null;
  client ??= new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  return client;
}
async function generateJson(input, schema) {
  const started = Date.now();
  const ai = getClient();
  if (!ai) {
    return { value: null, latencyMs: 0, model: MODEL, error: "GEMINI_API_KEY not set" };
  }
  try {
    const interaction = await Promise.race([
      ai.interactions.create({
        model: MODEL,
        input,
        response_format: {
          type: "text",
          mime_type: "application/json",
          schema
        }
      }),
      new Promise(
        (_, reject) => setTimeout(() => reject(new Error("timeout")), TIMEOUT_MS)
      )
    ]);
    if (interaction.status !== "completed") {
      return {
        value: null,
        latencyMs: Date.now() - started,
        model: MODEL,
        error: `status ${interaction.status}`
      };
    }
    const text = interaction.output_text;
    if (!text) {
      return { value: null, latencyMs: Date.now() - started, model: MODEL, error: "empty output" };
    }
    return { value: JSON.parse(text), latencyMs: Date.now() - started, model: MODEL };
  } catch (err) {
    return {
      value: null,
      latencyMs: Date.now() - started,
      model: MODEL,
      error: err instanceof Error ? err.message : "unknown"
    };
  }
}

// server/lib/prompt.ts
var TAXONOMY = MISCONCEPTION_IDS.map((id) => `  ${id} \u2014 ${MISCONCEPTION_LABELS[id]}`).join("\n");
var DIAGNOSIS_SYSTEM = `You are diagnosing a beginner's understanding of the Two Sum problem.

You are NOT grading their code. You are naming the single misunderstanding that best
explains what they wrote. Choose exactly one id from this list:

${TAXONOMY}

Rules:
- Judge the IDEA, not the syntax. A correct hash-map approach with a typo is NONE.
- A working brute-force solution is still TS_BRUTE_FORCE_ONLY. Working is not the bar.
- If they describe the right approach in words but have not written it yet, that is NONE.
- If two apply, pick the one that is furthest upstream \u2014 the one that, once fixed,
  makes the other disappear.
- If nothing fits, or you are guessing, return NONE with a low confidence rather than
  inventing a misconception. A wrong diagnosis is worse than no diagnosis.`;
var DIAGNOSIS_SCHEMA = {
  type: "object",
  properties: {
    misconceptionId: { type: "string", enum: [...MISCONCEPTION_IDS] },
    confidence: { type: "number" },
    evidence: {
      type: "string",
      description: "One short sentence quoting what in their work led you here."
    }
  },
  required: ["misconceptionId", "confidence", "evidence"]
};
function buildDiagnosisInput(problem, attempt) {
  return `${DIAGNOSIS_SYSTEM}

PROBLEM
${problem.statement.slice(0, 1200)}

WHAT THE LEARNER SAID
${attempt.text || "(nothing yet)"}

THEIR CODE
${problem.code ? problem.code.slice(0, 1500) : "(editor is empty)"}`;
}
var COACH_SYSTEM = `You are a patient coding coach. You teach by asking, not by telling.

HARD RULES \u2014 breaking any one of these fails the response:
- Never give the solution, in code or in prose. Never name the data structure that
  solves the problem. The learner has to arrive there themselves.
- Never write more than 3 lines of code, and only ever to point at something they
  already wrote.
- Sound like a person talking, not documentation. Short sentences. No bullet lists.
- Never open with praise you do not mean, and never open with "Great question".
- Lead with what is RIGHT about their thinking before you point anywhere else.`;
var MODALITY_BRIEF = {
  question: "Ask ONE question that makes them notice the gap themselves. No content, no hint at the answer. It must end in a question mark.",
  analogy: "Give a short real-life comparison \u2014 a coat check, a guest list, a phone book. Do NOT mention arrays, maps, dictionaries, hashes, or indices anywhere in it. End by asking what the comparison maps onto in their code.",
  visual: "Introduce the diagram they are about to see in one or two sentences. Tell them what to watch for. Do not describe the whole algorithm.",
  video: "Hand off to the video warmly and specifically \u2014 say what the clip will show them that you have not managed to. Keep it to two sentences."
};
var COACH_SCHEMA = {
  type: "object",
  properties: {
    message: { type: "string" },
    analogy: { type: "string", description: 'Only when the modality is analogy. Otherwise "".' },
    comprehensionQuestion: {
      type: "string",
      description: 'Only when asked for. A question they answer in one sentence. Otherwise "".'
    },
    expectedIdea: {
      type: "string",
      description: 'What a correct answer to the comprehension question contains. Otherwise "".'
    }
  },
  required: ["message", "analogy", "comprehensionQuestion", "expectedIdea"]
};
function buildCoachInput(problem, attempt, misconceptionId, intervention) {
  const doNotRepeat = intervention.doNotRepeat.length ? intervention.doNotRepeat.map((m) => `- "${m}"`).join("\n") : "(nothing yet)";
  const exhaustion = intervention.exhausted ? "\nYou have already tried every approach on this misunderstanding. Say so honestly, and ask them to explain their thinking back to you from the beginning." : "";
  return `${COACH_SYSTEM}

THE MISUNDERSTANDING YOU ARE ADDRESSING
${misconceptionId} \u2014 ${MISCONCEPTION_LABELS[misconceptionId]}

WHAT YOU ARE DOING THIS TURN (chosen for you \u2014 do not deviate)
Hint level: ${intervention.hintLevel ?? "past the ladder"} of 4
Mode: ${intervention.modality}
${MODALITY_BRIEF[intervention.modality]}${exhaustion}
${intervention.askComprehension ? "\nAlso ask ONE comprehension question they can answer in a sentence." : ""}

YOU HAVE ALREADY SAID THESE THINGS. Do not repeat them, do not rephrase them,
do not make the same point with different words:
${doNotRepeat}

PROBLEM
${problem.statement.slice(0, 800)}

WHAT THE LEARNER SAID
${attempt.text || "(they pressed a help button rather than typing)"}

THEIR CODE
${problem.code ? problem.code.slice(0, 1200) : "(editor is empty)"}`;
}

// server/lib/skills.ts
var SKILL_FOR = {
  TS_BRUTE_FORCE_ONLY: "hash_maps",
  TS_COMPLEMENT_CONFUSION: "problem_decomposition",
  TS_MAP_DIRECTION_FLIPPED: "hash_maps",
  TS_INSERT_BEFORE_CHECK: "hash_maps",
  TS_RETURNS_VALUES_NOT_INDICES: "problem_decomposition",
  TS_OFF_BY_ONE_INNER_LOOP: "array_traversal",
  NONE: null
};

// server/lib/validate.ts
var CODE_LINE = /(^|\s)(for|while|if|return|def|function|const|let|var|class)\s|[{};]\s*$|=>|\w+\[[^\]]*\]\s*=/;
function countCodeLines(message) {
  let total = 0;
  const fences = message.match(/```[\s\S]*?```/g) ?? [];
  for (const block of fences) {
    total += block.split("\n").length - 2;
  }
  const withoutFences = message.replace(/```[\s\S]*?```/g, "");
  for (const line of withoutFences.split("\n")) {
    if (CODE_LINE.test(line.trim())) total += 1;
  }
  return total;
}
function rejectionFor(value) {
  if (typeof value !== "object" || value === null) {
    return { reason: "not an object" };
  }
  const r = value;
  if (!MISCONCEPTION_IDS.includes(r.misconceptionId)) {
    return { reason: `unknown misconceptionId: ${String(r.misconceptionId)}` };
  }
  if (typeof r.message !== "string" || r.message.trim().length < 10) {
    return { reason: "message missing or too short" };
  }
  if (!MODALITIES.includes(r.modality)) {
    return { reason: `unknown modality: ${String(r.modality)}` };
  }
  if (!Array.isArray(r.offeredActions) || r.offeredActions.some((a) => !HELP_ACTIONS.includes(a))) {
    return { reason: "offeredActions contains something that is not a HelpAction" };
  }
  if (typeof r.confidence !== "number" || r.confidence < 0 || r.confidence > 1) {
    return { reason: "confidence out of range" };
  }
  const codeLines = countCodeLines(r.message);
  if (codeLines > MAX_CODE_LINES_IN_RESPONSE) {
    return { reason: `answered with ${codeLines} lines of code` };
  }
  if (r.hintLevel === 1 && !r.message.trim().endsWith("?")) {
    return { reason: "L1 hint did not end in a question" };
  }
  return null;
}

// server/lib/visualSpec.ts
function buildTwoSumVisual(values) {
  const { nums, target } = values;
  const steps = [];
  const seen = /* @__PURE__ */ new Map();
  const rows = (highlightKey, state = "idle") => [...seen.entries()].map(([key, value]) => ({
    key,
    value,
    state: key === highlightKey ? state : "idle"
  }));
  steps.push({
    caption: "We walk the array once. Alongside it we keep a table of every number we have already seen, and where we saw it.",
    activeIndex: null,
    processedIndices: [],
    map: [],
    highlight: "none"
  });
  for (let i = 0; i < nums.length; i += 1) {
    const n = nums[i];
    const complement = target - n;
    const processed = Array.from({ length: i }, (_, k) => k);
    steps.push({
      caption: `i = ${i}. The number here is ${n}.`,
      activeIndex: i,
      processedIndices: processed,
      map: rows(),
      highlight: "active"
    });
    if (seen.has(complement)) {
      steps.push({
        caption: "One lookup \u2014 not a scan of everything to the right.",
        activeIndex: i,
        processedIndices: processed,
        map: rows(complement, "matched"),
        highlight: "match",
        note: `${target} - ${n} = ${complement} \u2014 and ${complement} is right there, at index ${seen.get(complement)}.`
      });
      steps.push({
        caption: `Two indices, one pass. We never had to look at what comes after index ${i}.`,
        activeIndex: i,
        processedIndices: processed,
        map: rows(complement, "matched"),
        highlight: "match",
        note: `return [${seen.get(complement)}, ${i}]`
      });
      return { kind: "hash_map_fill", title: "One pass, one lookup table", values, steps };
    }
    steps.push({
      caption: i === 0 ? "Before storing anything, ask the table a question: have I already seen the partner this number needs?" : "Same question, every time. Ask first, store second.",
      activeIndex: i,
      processedIndices: processed,
      map: rows(),
      highlight: "miss",
      note: `${target} - ${n} = ${complement} \u2014 is ${complement} in the table?`
    });
    seen.set(n, i);
    steps.push({
      caption: `Not there. Store ${n} and where it lives, then move on.`,
      activeIndex: i,
      processedIndices: processed,
      map: rows(n, "just_added"),
      highlight: "none",
      note: `${n} \u2192 index ${i}`
    });
  }
  steps.push({
    caption: "We reached the end without a match. For this input there is no pair.",
    activeIndex: null,
    processedIndices: nums.map((_, i) => i),
    map: rows(),
    highlight: "none"
  });
  return { kind: "hash_map_fill", title: "One pass, one lookup table", values, steps };
}

// visuals/videos.ts
var VIDEO_MAP = {};

// server/api/coach.ts
var config = { runtime: "edge" };
var CORS = {
  "content-type": "application/json",
  "access-control-allow-origin": "*",
  "access-control-allow-headers": "content-type",
  "access-control-allow-methods": "POST, OPTIONS"
};
var json = (body) => new Response(JSON.stringify(body), { status: 200, headers: CORS });
async function handler(req) {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
  let payload;
  try {
    payload = await req.json();
  } catch {
    return json(fallbackFor("NONE", { note: "unparseable request" }));
  }
  const { problem, attempt, profile } = payload;
  if (!problem || !attempt || !profile) {
    return json(fallbackFor("NONE", { note: "incomplete request" }));
  }
  const diag = await generateJson(
    buildDiagnosisInput(problem, attempt),
    DIAGNOSIS_SCHEMA
  );
  const misconceptionId = diag.value && diag.value.confidence >= CONFIDENCE_FLOOR ? diag.value.misconceptionId : "NONE";
  const projected = {
    ...profile,
    misconceptionCounts: {
      ...profile.misconceptionCounts,
      ...misconceptionId !== "NONE" ? { [misconceptionId]: countFor(profile, misconceptionId) + 1 } : {}
    }
  };
  const intervention = decideIntervention(projected, misconceptionId);
  const wasStuck = profile.lastIntervention !== null;
  const corrected = wasStuck && misconceptionId === "NONE";
  const written = await generateJson(
    buildCoachInput(problem, attempt, misconceptionId, intervention),
    COACH_SCHEMA
  );
  const candidate = written.value ? assemble(payload, misconceptionId, intervention, written.value, corrected, {
    model: written.model,
    latencyMs: diag.latencyMs + written.latencyMs
  }) : null;
  const rejection = candidate ? rejectionFor(candidate) : { reason: written.error ?? "no output" };
  if (!candidate || rejection) {
    const fb = fallbackFor(misconceptionId, {
      hintLevel: intervention.hintLevel,
      modality: "question",
      offeredActions: intervention.offeredActions,
      note: rejection?.reason
    });
    fb.blockedActions = intervention.blockedActions;
    fb.profileDelta.summary = summariseProfile(
      applyProfileDelta(profile, fb.profileDelta, Date.now())
    );
    return json(fb);
  }
  return json(candidate);
}
function assemble(payload, misconceptionId, intervention, written, corrected, meta) {
  const { problem, profile } = payload;
  const skill = SKILL_FOR[misconceptionId];
  const skillUpdates = {};
  if (skill) skillUpdates[skill] = "struggling";
  if (corrected && profile.lastIntervention) {
    const healed = SKILL_FOR[profile.lastIntervention.misconceptionId];
    if (healed) skillUpdates[healed] = "improving";
  }
  const delta = {
    skillUpdates,
    incrementMisconception: misconceptionId === "NONE" ? null : misconceptionId,
    recordDelivered: misconceptionId === "NONE" ? null : { misconceptionId, modality: intervention.modality },
    creditModality: creditFor(profile, corrected),
    appendCoachMessage: written.message,
    summary: ""
  };
  delta.summary = summariseProfile(applyProfileDelta(profile, delta, Date.now()));
  const values = problem.sampleInput ?? { nums: [2, 7, 11, 15], target: 9 };
  const video = VIDEO_MAP[misconceptionId] ?? null;
  return {
    misconceptionId,
    confidence: intervention.exhausted ? CONFIDENCE_FLOOR : 0.9,
    message: written.message,
    hintLevel: intervention.hintLevel,
    modality: intervention.modality,
    offeredActions: intervention.offeredActions,
    blockedActions: intervention.blockedActions,
    analogy: intervention.modality === "analogy" ? written.analogy || null : null,
    visual: intervention.modality === "visual" ? buildTwoSumVisual(values) : null,
    video: intervention.modality === "video" ? video : null,
    comprehensionQuestion: intervention.askComprehension && written.comprehensionQuestion ? {
      id: `${misconceptionId}-${intervention.hintLevel ?? "x"}`,
      prompt: written.comprehensionQuestion,
      expectedIdea: written.expectedIdea
    } : null,
    profileDelta: delta,
    learningGoal: LEARNING_GOALS[misconceptionId],
    meta: { fallbackUsed: false, model: meta.model, latencyMs: meta.latencyMs }
  };
}
export {
  config,
  handler as default
};
